/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stores */
        get: operations["list_stores_api_v1_stores_get"];
        put?: never;
        /** Create Store */
        post: operations["create_store_api_v1_stores_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{store_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Store */
        get: operations["get_store_api_v1_stores__store_id__get"];
        put?: never;
        post?: never;
        /** Delete Store */
        delete: operations["delete_store_api_v1_stores__store_id__delete"];
        options?: never;
        head?: never;
        /** Update Store */
        patch: operations["update_store_api_v1_stores__store_id__patch"];
        trace?: never;
    };
    "/api/v1/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cameras */
        get: operations["list_cameras_api_v1_cameras_get"];
        put?: never;
        /** Create Camera */
        post: operations["create_camera_api_v1_cameras_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/{camera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Camera */
        get: operations["get_camera_api_v1_cameras__camera_id__get"];
        put?: never;
        post?: never;
        /** Delete Camera */
        delete: operations["delete_camera_api_v1_cameras__camera_id__delete"];
        options?: never;
        head?: never;
        /** Update Camera */
        patch: operations["update_camera_api_v1_cameras__camera_id__patch"];
        trace?: never;
    };
    "/api/v1/clips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clips */
        get: operations["list_clips_api_v1_clips_get"];
        put?: never;
        /**
         * Upload Clip
         * @description Multipart upload of an mp4. Triggers sentry-ai via separate /verify call.
         */
        post: operations["upload_clip_api_v1_clips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clips/{clip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clip */
        get: operations["get_clip_api_v1_clips__clip_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clips/{clip_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Clip */
        get: operations["download_clip_api_v1_clips__clip_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alert Stream
         * @description SSE stream of new alerts for the current org.
         *
         *     Frontend usage:
         *         const es = new EventSource('/api/v1/alerts/stream', { withCredentials: true });
         *         es.addEventListener('alert', e => { const data = JSON.parse(e.data); ... });
         */
        get: operations["alert_stream_api_v1_alerts_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alert */
        get: operations["get_alert_api_v1_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Feedback */
        post: operations["post_feedback_api_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Alert From Ai
         * @description sentry-ai POSTs here after VLM verification finishes.
         *
         *     We derive store/camera/org from the clip — sentry-ai doesn't need to
         *     know the tenancy hierarchy.
         */
        post: operations["create_alert_from_ai_api_v1_internal_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/live-metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive Live Metadata
         * @description sentry-ai live worker POSTs batched per-frame metadata here.
         *
         *     Each frame is (a) dispatched to subscribers of its `camera_id` (browser
         *     WebSocket clients on `/ws/live/{camera_id}`) and (b) fed through the
         *     threshold handler to fire alerts on sustained risk_pct breaches (L5).
         */
        post: operations["receive_live_metadata_api_v1_internal_live_metadata_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_v1_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orgs */
        get: operations["list_orgs_api_v1_admin_orgs_get"];
        put?: never;
        /** Create Org */
        post: operations["create_org_api_v1_admin_orgs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orgs/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Org */
        get: operations["get_org_api_v1_admin_orgs__org_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orgs/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Org Members */
        get: operations["list_org_members_api_v1_admin_orgs__org_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        /** Invite User */
        post: operations["invite_user_api_v1_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/behaviors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Behavior Config
         * @description Current global behavior config. Public (any authenticated context can poll).
         */
        get: operations["get_behavior_config_api_v1_behaviors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Behavior Config
         * @description Update weights and/or thresholds. Auth required.
         */
        patch: operations["patch_behavior_config_api_v1_behaviors_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminStats
         * @description Top-level counts for the super-admin dashboard.
         */
        AdminStats: {
            /** Orgs */
            orgs: number;
            /** Users */
            users: number;
            /** Stores */
            stores: number;
            /** Cameras */
            cameras: number;
            /** Alerts */
            alerts: number;
        };
        /**
         * AlertCategory
         * @enum {string}
         */
        AlertCategory: "browsing" | "cart_pickup" | "pocket_conceal" | "other";
        /**
         * AlertCreateInternal
         * @description POST /api/v1/internal/alerts — sentry-ai service posts this.
         */
        AlertCreateInternal: {
            /**
             * Clip Id
             * Format: uuid
             */
            clip_id: string;
            category: components["schemas"]["AlertCategory"];
            /** Confidence */
            confidence: number;
            /** Reasoning */
            reasoning: string;
            /** Model Name */
            model_name: string;
            /** Inference Latency Ms */
            inference_latency_ms: number;
        };
        /**
         * AlertLevel
         * @enum {string}
         */
        AlertLevel: "ignore" | "log" | "notify" | "review";
        /** AlertPublic */
        AlertPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Clip Id
             * Format: uuid
             */
            clip_id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Store Id */
            store_id: string | null;
            /** Camera Id */
            camera_id: string | null;
            category: components["schemas"]["AlertCategory"];
            /** Confidence */
            confidence: number;
            /** Reasoning */
            reasoning: string;
            /** Model Name */
            model_name: string;
            alert_level: components["schemas"]["AlertLevel"];
            /** Inference Latency Ms */
            inference_latency_ms: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** @default manual_upload */
            triggered_by: components["schemas"]["AlertTrigger"];
            /** Person Id */
            person_id?: number | null;
            /** Peak Risk Pct */
            peak_risk_pct?: number | null;
        };
        /**
         * AlertTrigger
         * @enum {string}
         */
        AlertTrigger: "manual_upload" | "live_threshold";
        /** BehaviorConfig */
        BehaviorConfig: {
            /** Dimensions */
            dimensions: components["schemas"]["BehaviorDimension"][];
            /** Thresholds */
            thresholds: {
                [key: string]: number;
            };
            /**
             * Color Labels
             * @default {
             *       "green": "Хэвийн",
             *       "yellow": "Анхаар",
             *       "red": "Сэжигтэй"
             *     }
             */
            color_labels: {
                [key: string]: string;
            };
        };
        /**
         * BehaviorConfigPatch
         * @description Partial update — any subset of {weights, thresholds}.
         */
        BehaviorConfigPatch: {
            /**
             * Weights
             * @description Map of dimension key → new weight. Unknown keys rejected.
             */
            weights?: {
                [key: string]: number;
            } | null;
            /**
             * Thresholds
             * @description Subset of {green_max, yellow_max}. Both ≥ 0; green_max < yellow_max.
             */
            thresholds?: {
                [key: string]: number;
            } | null;
        };
        /** BehaviorDimension */
        BehaviorDimension: {
            /** Key */
            key: string;
            /** Label Mn */
            label_mn: string;
            /** Description Mn */
            description_mn: string;
            /** Weight */
            weight: number;
            /** Active In M1 */
            active_in_m1: boolean;
            /** Why Deferred */
            why_deferred: string | null;
        };
        /** Body_upload_clip_api_v1_clips_post */
        Body_upload_clip_api_v1_clips_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /**
             * Store Id
             * Format: uuid
             */
            store_id: string;
            /** Camera Id */
            camera_id?: string | null;
            /** Captured At */
            captured_at?: string | null;
            /**
             * Duration Sec
             * @default 0
             */
            duration_sec: number;
        };
        /** CameraCreate */
        CameraCreate: {
            /**
             * Store Id
             * Format: uuid
             */
            store_id: string;
            /** Name */
            name: string;
            /** Rtsp Url */
            rtsp_url?: string | null;
            /** Shelf Zone Json */
            shelf_zone_json?: {
                [key: string]: unknown;
            } | null;
            /**
             * Stage2 Threshold
             * @default 0.5
             */
            stage2_threshold: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Mediamtx Path */
            mediamtx_path?: string | null;
            /**
             * Risk Threshold
             * @default 70
             */
            risk_threshold: number;
        };
        /**
         * CameraPublic
         * @description Public Camera — `rtsp_url` NEVER exposed; only a boolean `has_rtsp_url`.
         */
        CameraPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Store Id
             * Format: uuid
             */
            store_id: string;
            /** Name */
            name: string;
            /** Shelf Zone Json */
            shelf_zone_json: {
                [key: string]: unknown;
            } | null;
            /** Stage2 Threshold */
            stage2_threshold: number;
            /** Enabled */
            enabled: boolean;
            /** Has Rtsp Url */
            has_rtsp_url: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Mediamtx Path */
            mediamtx_path?: string | null;
            /**
             * Risk Threshold
             * @default 70
             */
            risk_threshold: number;
        };
        /** CameraUpdate */
        CameraUpdate: {
            /** Name */
            name?: string | null;
            /** Rtsp Url */
            rtsp_url?: string | null;
            /** Shelf Zone Json */
            shelf_zone_json?: {
                [key: string]: unknown;
            } | null;
            /** Stage2 Threshold */
            stage2_threshold?: number | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Mediamtx Path */
            mediamtx_path?: string | null;
            /** Risk Threshold */
            risk_threshold?: number | null;
        };
        /** ClipPublic */
        ClipPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Store Id */
            store_id: string | null;
            /** Camera Id */
            camera_id: string | null;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Duration Sec */
            duration_sec: number;
            /** File Size Bytes */
            file_size_bytes: number;
            /** Sha256 */
            sha256: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FeedbackCreate */
        FeedbackCreate: {
            /**
             * Alert Id
             * Format: uuid
             */
            alert_id: string;
            verdict: components["schemas"]["FeedbackVerdict"];
            /** Notes */
            notes?: string | null;
        };
        /** FeedbackPublic */
        FeedbackPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Alert Id
             * Format: uuid
             */
            alert_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            verdict: components["schemas"]["FeedbackVerdict"];
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FeedbackVerdict
         * @enum {string}
         */
        FeedbackVerdict: "true_positive" | "false_positive" | "unclear";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LiveMetadataBatch
         * @description Batch of per-frame metadata from sentry-ai live worker.
         */
        LiveMetadataBatch: {
            /** Frames */
            frames: {
                [key: string]: unknown;
            }[];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            user: components["schemas"]["UserPublic"];
            tokens: components["schemas"]["TokenPair"];
        };
        /**
         * OrgMemberPublic
         * @description A user together with their role inside one organization.
         */
        OrgMemberPublic: {
            user: components["schemas"]["UserPublic"];
            role: components["schemas"]["OrgRole"];
        };
        /**
         * OrgRole
         * @enum {string}
         */
        OrgRole: "owner" | "admin" | "staff";
        /** OrganizationCreate */
        OrganizationCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** OrganizationPublic */
        OrganizationPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StoreCreate */
        StoreCreate: {
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            /**
             * Timezone
             * @default Asia/Ulaanbaatar
             */
            timezone: string;
        };
        /** StorePublic */
        StorePublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Name */
            name: string;
            /** Address */
            address: string | null;
            /** Timezone */
            timezone: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StoreUpdate */
        StoreUpdate: {
            /** Name */
            name?: string | null;
            /** Address */
            address?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UserAdminUpdate
         * @description Partial update of a user's super-admin / active flags.
         *
         *     Both fields optional; only provided keys are applied.
         */
        UserAdminUpdate: {
            /** Is Active */
            is_active?: boolean | null;
            /** Is Super Admin */
            is_super_admin?: boolean | null;
        };
        /** UserInvite */
        UserInvite: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            role: components["schemas"]["OrgRole"];
            /**
             * Is Super Admin
             * @default false
             */
            is_super_admin: boolean;
        };
        /** UserPublic */
        UserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Is Super Admin */
            is_super_admin: boolean;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                sentry_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stores_api_v1_stores_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorePublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_store_api_v1_stores_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_store_api_v1_stores__store_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                store_id: string;
            };
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_store_api_v1_stores__store_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                store_id: string;
            };
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_store_api_v1_stores__store_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                store_id: string;
            };
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cameras_api_v1_cameras_get: {
        parameters: {
            query?: {
                store_id?: string | null;
            };
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_camera_api_v1_cameras_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_api_v1_cameras__camera_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                camera_id: string;
            };
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_camera_api_v1_cameras__camera_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                camera_id: string;
            };
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_camera_api_v1_cameras__camera_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                camera_id: string;
            };
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clips_api_v1_clips_get: {
        parameters: {
            query?: {
                store_id?: string | null;
                camera_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_clip_api_v1_clips_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_clip_api_v1_clips_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clip_api_v1_clips__clip_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                clip_id: string;
            };
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_clip_api_v1_clips__clip_id__download_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                clip_id: string;
            };
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                store_id?: string | null;
                camera_id?: string | null;
                min_level?: components["schemas"]["AlertLevel"] | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alert_stream_api_v1_alerts_stream_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_api_v1_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Org-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                alert_id: string;
            };
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_feedback_api_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Org-Id"?: string | null;
            };
            path?: never;
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_alert_from_ai_api_v1_internal_alerts_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertCreateInternal"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_live_metadata_api_v1_internal_live_metadata_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiveMetadataBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_v1_admin_stats_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orgs_api_v1_admin_orgs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_org_api_v1_admin_orgs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_org_api_v1_admin_orgs__org_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_org_members_api_v1_admin_orgs__org_id__members_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgMemberPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_user_api_v1_admin_users_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInvite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserAdminUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_behavior_config_api_v1_behaviors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BehaviorConfig"];
                };
            };
        };
    };
    patch_behavior_config_api_v1_behaviors_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sentry_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BehaviorConfigPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BehaviorConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
