/** App-facing domain types — DERIVED from the backend OpenAPI schema via
 * `src/lib/api.types.ts` (generated by `npm run codegen`). Re-exporting under
 * the same names keeps call sites unchanged while guaranteeing the shapes never
 * drift from the backend contract. Run codegen after backend changes; CI fails
 * on drift (`npm run codegen:check`). Only the convenience aliases are
 * hand-written. */

import type { components } from "./api.types";

type Schemas = components["schemas"];

// === Auth ===
export type UserPublic = Schemas["UserPublic"];
export type TokenPair = Schemas["TokenPair"];
export type LoginResponse = Schemas["LoginResponse"];

// === Org / admin ===
export type OrgRole = Schemas["OrgRole"];
export type OrganizationPublic = Schemas["OrganizationPublic"];
export type OrgMemberPublic = Schemas["OrgMemberPublic"];
export type AdminStats = Schemas["AdminStats"];
export type UserInviteInput = Schemas["UserInvite"];
export type UserAdminUpdate = Schemas["UserAdminUpdate"];

// === Behaviors (editable criteria catalog + risk thresholds) ===
export type BehaviorConfig = Schemas["BehaviorConfig"];
export type BehaviorConfigPatch = Schemas["BehaviorConfigPatch"];
export type BehaviorDimension = Schemas["BehaviorDimension"];
export type DimensionCreate = Schemas["DimensionCreate"];
export type DimensionUpdate = Schemas["DimensionUpdate"];

// === Leads (public landing demo requests) ===
export type LeadPublic = Schemas["LeadPublic"];
export type LeadStatus = Schemas["LeadStatus"];
export type LeadUpdate = Schemas["LeadUpdate"];

// === AI nodes (sentry-ai compute boxes) ===
export type AiNodePublic = Schemas["AiNodePublic"];
export type AiNodeUpdate = Schemas["AiNodeUpdate"];
export type AiNodePairingCode = Schemas["AiNodePairingCodePublic"];
