/** App-facing domain types — DERIVED from the backend OpenAPI schema via
 * `src/lib/api.types.ts` (generated by `npm run codegen`). Re-exporting under
 * the same names keeps call sites unchanged while guaranteeing the shapes never
 * drift from the backend contract. Run codegen after backend changes; CI fails
 * on drift (`npm run codegen:check`). Only the convenience aliases are
 * hand-written. */

import type { components } from "./api.types";

type Schemas = components["schemas"];

// === Auth ===
export type UserPublic = Schemas["UserPublic"];
// Tokens live only in httpOnly cookies (ADR-0017) — no TokenPair in the API body.
export type LoginResponse = Schemas["LoginResponse"];

// === Org / admin ===
export type OrgRole = Schemas["OrgRole"];
export type OrganizationPublic = Schemas["OrganizationPublic"];
export type OrgMemberPublic = Schemas["OrgMemberPublic"];
export type AdminStats = Schemas["AdminStats"];
export type UserInviteInput = Schemas["UserInvite"];
export type UserAdminUpdate = Schemas["UserAdminUpdate"];

// === Behaviors (editable criteria catalog + risk thresholds) ===
export type BehaviorConfig = Schemas["BehaviorConfig"];
export type BehaviorConfigPatch = Schemas["BehaviorConfigPatch"];
export type BehaviorDimension = Schemas["BehaviorDimension"];
export type DimensionCreate = Schemas["DimensionCreate"];
export type DimensionUpdate = Schemas["DimensionUpdate"];

// === Event / activity log ===
export type EventLogPublic = Schemas["EventLogPublic"];
export type EventType = Schemas["EventType"];
export type EventSeverity = Schemas["EventSeverity"];

// === Leads (public landing demo requests) ===
export type LeadPublic = Schemas["LeadPublic"];
export type LeadStatus = Schemas["LeadStatus"];
export type LeadUpdate = Schemas["LeadUpdate"];

// === AI nodes (sentry-ai compute boxes) ===
export type AiNodePublic = Schemas["AiNodePublic"];
export type AiNodeUpdate = Schemas["AiNodeUpdate"];
export type AiNodePairingCode = Schemas["AiNodePairingCodePublic"];

// === Billing (super-admin) ===
// HAND-WRITTEN: the committed OpenAPI snapshot predates the billing endpoints,
// so these mirror sentry-backend/src/sentry_backend/schemas/billing.py by hand.
// Replace with Schemas["..."] aliases after the next `npm run fetch-openapi`.

export type BillingStatus = "active" | "credit" | "suspended";
export type JournalKind = "topup" | "usage_charge" | "promo_credit" | "adjustment";
export type LedgerAccount = "cash" | "org_wallet" | "revenue" | "promo_expense";
export type PromoKind = "bonus_amount" | "free_days";

export interface OrgBillingRow {
  org_id: string;
  name: string;
  slug: string;
  balance_mnt: number;
  status: BillingStatus;
  daily_rate_mnt: number;
  stores_count: number;
  cameras_count: number;
  credit_until: string | null;
  promo_free_until: string | null;
  last_topup_at: string | null;
}

export interface BillingOverview {
  orgs: OrgBillingRow[];
  total_balance_mnt: number;
  total_daily_rate_mnt: number;
  active_count: number;
  credit_count: number;
  suspended_count: number;
}

export interface JournalEntryPublic {
  id: string;
  posted_at: string;
  kind: JournalKind;
  dr_account: LedgerAccount;
  cr_account: LedgerAccount;
  amount_mnt: number;
  description: string;
  charge_date: string | null;
  meta: Record<string, unknown> | null;
}

export interface TopupRequest {
  amount_mnt: number;
  note?: string | null;
}

export interface CreditRequest {
  until: string; // ISO datetime, must be in the future
  note?: string | null;
}

export interface PromoCodeCreate {
  code?: string | null; // omitted/blank → backend auto-generates
  kind: PromoKind;
  amount_mnt?: number | null; // required when kind=bonus_amount
  free_days?: number | null; // required when kind=free_days
  valid_until?: string | null; // null → no expiry
  max_redemptions?: number;
  note?: string | null;
}

export interface PromoCodeUpdate {
  active?: boolean | null;
  note?: string | null;
}

export interface PromoCodePublic {
  id: string;
  code: string;
  kind: PromoKind;
  amount_mnt: number | null;
  free_days: number | null;
  valid_until: string | null;
  max_redemptions: number;
  redeemed_count: number;
  active: boolean;
  note: string | null;
  created_at: string;
}

export interface BillingDayPoint {
  day: string; // ISO date (totals row carries the range key instead)
  usage_mnt: number;
  topup_mnt: number;
  promo_mnt: number;
}

export interface BillingAnalytics {
  by_day: BillingDayPoint[];
  totals: BillingDayPoint;
  suspended_count: number;
  credit_count: number;
}
